version: '3.8'

services:
  backend:
    image: restapiimage
    container_name: spring-boot-app
    ports:
      - "8096:8096"
    environment:
      SPRING_APPLICATION_NAME: RestApi_project
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pranav
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Pranav@2002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: pranav
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pranav@2002
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pranav"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: reactimage
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
